try {

} catch {
    console.log(error)
}